name: Convert XML to Markdown


permissions:
  contents: write  # Donne l'accès en écriture aux contenus du dépôt
  
# Ce workflow sera déclenché à chaque modification de fichiers XML dans le répertoire "data/"
on:
  push:
    paths:
      - 'INFILE/XML/*.xml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Cloner le dépôt
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Configurer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 3. Installer les dépendances Python, si nécessaire
    - name: Install dependencies
      run: |
        pip install openpyxl

    # 4. Exécuter le script Python sur chaque fichier XML du répertoire data/
    - name: Run XML to Markdown script
      run: |
        for file in INFILE/XML/*.xml; do
          python update.py "$file"
        done

    # 5. Ajouter et commettre le fichier Markdown généré
    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add **/*.md
        git commit -m "Generate Markdown from XML updates" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
